{
 "title": "Advanced_Power_Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Power History",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"power_monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"equipment_power_usage\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Power_kVA\")\n  |> filter(fn: (r) => r[\"machine\"] == \"Machine_1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Apparent Power, kVA",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kvoltamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"power_monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"equipment_power_usage\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Power_kVA\")\n  |> filter(fn: (r) => r[\"machine\"] == \"Machine_1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Current Phase 1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"power_monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"equipment_power_usage\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Current_1\")\n  |> filter(fn: (r) => r[\"machine\"] == \"Machine_1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Voltage Phase 1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"power_monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"equipment_power_usage\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Voltage_1\")\n  |> filter(fn: (r) => r[\"machine\"] == \"Machine_1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Current Phase 2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"power_monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"equipment_power_usage\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Current_2\")\n  |> filter(fn: (r) => r[\"machine\"] == \"Machine_1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Voltage Phase 2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"power_monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"equipment_power_usage\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Voltage_2\")\n  |> filter(fn: (r) => r[\"machine\"] == \"Machine_1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Current Phase 3",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"power_monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"equipment_power_usage\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Current_3\")\n  |> filter(fn: (r) => r[\"machine\"] == \"Machine_1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Voltage Phase 2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"power_monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"equipment_power_usage\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Voltage_3\")\n  |> filter(fn: (r) => r[\"machine\"] == \"Machine_1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}